### ISSUE TITLE
Perl Error when running update_blastdb.pl

### ISSUE THREAD

**Issue by jpeasari** [asadprodhan/blastn#1]
Can't locate Archive/Tar.pm in @INC (you may need to install the Archive::Tar module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at update_blastdb.pl line 41.
BEGIN failed--compilation aborted at update_blastdb.pl line 41.

**Comment by jpeasari** [comment]
Updating Perl Fixed.
Thank you

**Comment by asadprodhan** [comment]
Thanks for the update


*Dr Asad Prodhan **| *Laboratory Scientist- Bioinformatics

Adjunct Senior Lecturer | University of Western Australia

Adjunct Senior Lecturer | Murdoch University

Department of Primary Industries and Regional Development

*E* ***@***.*** ***@***.***>* | *W* asadprodhan.github.io


GitHub <https://github.com/asadprodhan> | Google Scholar
<https://scholar.google.com.au/citations?hl=en&user=ZQzQadIAAAAJ&view_op=list_works&sortby=pubdate>
 | ResearchGate <https://www.researchgate.net/profile/Asad-Prodhan> | ORCiD
<https://orcid.org/0000-0002-1320-3486> | Twitter
<https://x.com/Asad_Prodhan> | LinkedIn
<https://www.linkedin.com/in/asadprodhan/>
